### ISSUE TITLE
revert memory

### ISSUE THREAD

**Issue by fidel-bello** [fidel-bello/camera_angles_mod#14]
- need to figure out a way to revert the changed nop
- will be helpful when users would like to change back to the default camera angle
- was thinking this could be done by setting an int as the ReadProcessMemory and pushing it back to writeProcessMemory ? 
```c++
 char defaultArray = ReadProcessMemory();
```
- could that even work?
- let's find out

**Comment by fidel-bello** [comment]
- testing and I believe this method is incorrect
- maybe storing the original data?

**Comment by delinx** [comment]
Yes you can read memory like that, however the return wouldn't do it, you need to pass pointer to buffer it can write to as an argument

Useful thing to google:
How to read process memory into buffer

**Comment by fidel-bello** [comment]
haha yes! i was looking for that google keyword
