### ISSUE TITLE
module base address

### ISSUE THREAD

**Issue by fidel-bello** [fidel-bello/camera_angles_mod#4]
-  to read process memory from windows api we need to pass in HANDLE hProcess, LPCVOID lpBaseAddress, LPVOID lpBuffer, SIZE_T nSize, SIZE_T *lpNumberOfBytesRead

``` c++
ReadProcessMemory(l_handle, modInfo.lpBaseOfDll, &zoomVal, sizeof(zoomVal), nullptr);
````
- is this how you would do it?
- im having issues understanding this part. how could we add offsets to the baseDll

**Comment by delinx** [comment]
Crazily enough I think we need no functions to read or writer, I would love to experiment when you are available

**Comment by fidel-bello** [comment]
Available now, let me get to my old faithful

**Comment by delinx** [comment]
> Available now, let me get to my old faithful 

I will come online in 10 minutes or so, woke up with even worst headache so need to do something till pills kick in

**Comment by fidel-bello** [comment]
thank you @delinx your past solutions really worked. on to the next step
